import PVcard from "../PVcard";
import "./index.css";

export default function PVlist() {

    const portaVozes = [
    {
        name: "Renan Santos",
        desc: "Fundador do MBL e presidente da Missão. Detrator oficial do governo e zagueiro da FFF.",
        seguidores: "+120 mil Seguidores",
        instagram: "https://www.instagram.com/renansantosmbl/",
        x: "https://x.com/RenanSantosMBL",
        src: "https://framerusercontent.com/images/0sElXq3wbcucPtdD2mxR9gypgM.webp",
        alt: "Renan Santos",
        tags: ["Nacional", "Sudeste"],
    },
    {
        name: "Kim Kataguiri",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Arthur do Val",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Guto Zacarias",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
        {
        name: "Amanda Vettorazzo",
        desc: "Vereadora de São Paulo. Coordenadora nacional MBL. Gestora Pública. Pós-grad. Cidades Inteligentes.",
        votos: "+40 mil Votos",
        seguidores: "+1 mi Seguidores",
        instagram: "https://www.instagram.com/amanda.vettorazzo/",
        youtube: "https://www.youtube.com/@AmandaVettorazzosp",
        x: "https://x.com/Amandavettorazz",
        src: "https://framerusercontent.com/images/JMB8hm0fqCY4kWoO6Rz3wUQTO0.webp",
        alt: "Amanda",
        tags: ["Vereadora", "Nacional", "Sudeste"],
    },
    {
        name: "Cristiano Beraldo",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Jota",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Paulo Cruz",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Renato Battista",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Ricardo Almeida",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Juliana Lima",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Rafael Minatoawa",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Bruno Zancheta",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Gabriel Tomazini",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Israel Russo",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Italo Moreira",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Luana Silva",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Lucas Pires",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Mateus Batista",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Matheus Faustino",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Paulo Filipe",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Pedro Duarte",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Sandro Filho",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Andrei Castro",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Arthur Scara",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Gustavo Camillo",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Pedro Arthur",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Rafa Macris",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
    {
        name: "Sávio Rodrigues",
        desc: "",
        votos: "",
        seguidores: "",
        instagram: "",
        youtube: "",
        x: "",
        src: "",
        alt: "",
        tags: [],
    },
];
  return (<div className="pvlist-container">
    <div className="pvlist-buttons">
        <p className="pvlist-button">Todos</p>
        <p className="pvlist-button">A-Z</p>
        <p className="pvlist-button">Nacional</p>
        <p className="pvlist-button">Nordeste</p>
        <p className="pvlist-button">Sudeste</p>
        <p className="pvlist-button">Sul</p>
        <p className="pvlist-button">Dep. Federal</p>
        <p className="pvlist-button">Dep. Estadual</p>
        <p className="pvlist-button">Vice-Prefeita</p>
        <p className="pvlist-button">Vereadores</p>
    </div>
    <div className="pvlist">
        { portaVozes.map((portaVoz, index) => (
            <PVcard
                key={index}
                name={portaVoz.name}
                desc={portaVoz.desc}
                votos={portaVoz.votos}
                seguidores={portaVoz.seguidores}
                instagram={portaVoz.instagram}
                youtube={portaVoz.youtube}
                x={portaVoz.x}
                src={portaVoz.src}
                alt={portaVoz.alt}
                tags={portaVoz.tags}
            />
        ))

        }
    </div>


  </div>);
}